# Copy into a repo as .github/workflows/claim-issue.yml
name: Claim Issue

on:
  issue_comment:
    types: [created]

jobs:
  call:
    permissions:
      issues: write
    uses: avalon-initiative/.github/.github/workflows/claim-issue.yml@main
